# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blip' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blip
  pod 'lottie-ios'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Pastel'
  pod 'IBAnimatable'
  pod 'Material'
  pod 'Alamofire'
  pod 'Mapbox-iOS-SDK'
  pod 'MapboxCoreNavigation'
  pod 'PopupDialog'
  pod 'Stripe'
  pod 'Kingfisher'
  pod 'RevealingSplashView'
  pod 'Firebase/Storage'
  pod 'CHIPageControl/Fresno'
  pod 'NotificationBannerSwift'
  pod 'Cosmos'
  pod 'BSImagePicker'
  pod 'SwiftIcons'
  pod 'Hero'
  pod 'SRCountdownTimer'
  pod 'Pulsator'
  pod 'Eureka'
  pod "Floaty"

  target 'BlipTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlipUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
